// Re-export all components with explicit index.js paths
export * from './core/index.js'
export * from './brand/index.js'
export * from './data/index.js'
export * from './data-table/index.js'
export * from './interaction/index.js'
export * from './overlay/index.js'
export * from './utility/index.js'
export * from './resizable/index.js'

// New component categories
export * from './surface/index.js'
export * from './feedback/index.js'
export * from './file/index.js'
export * from './code/index.js'
export * from './motion/index.js'
export * from './marketing/index.js'
export * from './layout/index.js'
export * from './markdown/index.js'
export * from './errors/index.js'
