/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectSummarizationRouteImport } from './routes/project-summarization'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueDashboardQueueIdRouteImport } from './routes/queue-dashboard.$queueId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSummarizationRoute = ProjectSummarizationRouteImport.update({
  id: '/project-summarization',
  path: '/project-summarization',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueDashboardQueueIdRoute = QueueDashboardQueueIdRouteImport.update({
  id: '/queue-dashboard/$queueId',
  path: '/queue-dashboard/$queueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/health': typeof HealthRoute
  '/project-summarization': typeof ProjectSummarizationRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/queue-dashboard/$queueId': typeof QueueDashboardQueueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/health': typeof HealthRoute
  '/project-summarization': typeof ProjectSummarizationRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/queue-dashboard/$queueId': typeof QueueDashboardQueueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/health': typeof HealthRoute
  '/project-summarization': typeof ProjectSummarizationRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/queue-dashboard/$queueId': typeof QueueDashboardQueueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/chat'
    | '/health'
    | '/project-summarization'
    | '/projects'
    | '/prompts'
    | '/providers'
    | '/settings'
    | '/queue-dashboard/$queueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/chat'
    | '/health'
    | '/project-summarization'
    | '/projects'
    | '/prompts'
    | '/providers'
    | '/settings'
    | '/queue-dashboard/$queueId'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/chat'
    | '/health'
    | '/project-summarization'
    | '/projects'
    | '/prompts'
    | '/providers'
    | '/settings'
    | '/queue-dashboard/$queueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  ChatRoute: typeof ChatRoute
  HealthRoute: typeof HealthRoute
  ProjectSummarizationRoute: typeof ProjectSummarizationRoute
  ProjectsRoute: typeof ProjectsRoute
  PromptsRoute: typeof PromptsRoute
  ProvidersRoute: typeof ProvidersRoute
  SettingsRoute: typeof SettingsRoute
  QueueDashboardQueueIdRoute: typeof QueueDashboardQueueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-summarization': {
      id: '/project-summarization'
      path: '/project-summarization'
      fullPath: '/project-summarization'
      preLoaderRoute: typeof ProjectSummarizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue-dashboard/$queueId': {
      id: '/queue-dashboard/$queueId'
      path: '/queue-dashboard/$queueId'
      fullPath: '/queue-dashboard/$queueId'
      preLoaderRoute: typeof QueueDashboardQueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  ChatRoute: ChatRoute,
  HealthRoute: HealthRoute,
  ProjectSummarizationRoute: ProjectSummarizationRoute,
  ProjectsRoute: ProjectsRoute,
  PromptsRoute: PromptsRoute,
  ProvidersRoute: ProvidersRoute,
  SettingsRoute: SettingsRoute,
  QueueDashboardQueueIdRoute: QueueDashboardQueueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
