export {
  DynamicAdapter,
  createDynamicAdapter,
  DynamicAdapterLive,
  AdaptationServiceTag,
  AdaptationError,
  type AdaptationService,
  type AdaptationContext,
  type UserPreferences,
  type PerformanceMetrics,
  type EnvironmentState,
  type ModelCapabilities,
  type ResourceConstraints,
  type ApiQuota,
  type FeedbackEntry,
  type AdaptationStrategy,
  type AdaptationTrigger,
  type AdaptationAction,
  type AdaptedPrompt,
  type Modification,
  type AdaptationMetadata,
  type PerformanceEstimate,
  type AdaptationMetrics
} from './dynamic-adapter'
